### ISSUE TITLE
how can i crawl post 

### ISSUE THREAD

**Issue by fengfangqian** [rolando/scrapy-redis#101]
curl -H "Content-Type:application/json" -d '{"body":{"sdkVersionCode": 0, "pkgNameList": ["com.sinyee.babybus.show"]},"head":{"nonce": 6372210978, "timestamp": 1496299869, "callbackPara": "callback01", "businessId": "test"}}' "http://maapi.3g.qq.com:8080/v1/getAppDetailBatch?output=json&signature=58f2e5e11efd48ad4c7276835516d265"

like this url

**Comment by rolando** [comment]
As a start url not possible unless you change the deserialization here: https://github.com/rolando/scrapy-redis/blob/master/src/scrapy_redis/spiders.py#L97
