### ISSUE TITLE
when using (RedisMixin,CrawlSpider) instead of RedisSpider, the spider doesn't work

### ISSUE THREAD

**Issue by Aprilara** [rolando/scrapy-redis#38]
When scraping, if I use 
class MyCrawler(RedisMixin, CrawlSpider) ,
and run my crawler by "scrapy crawl mycrawler", the crawler just automatically shutdown in a minite without any exceptions or errors.

But if a use 
class mySpider(RedisSpider), it works well.

Is there any problem with CrawlSpider in scrapy-redis?

**Comment by rolando** [comment]
Sorry for such late reply. I think this should be fixed in the latest version.
