### ISSUE TITLE
分布式爬虫爬取多个网站的新闻

### ISSUE THREAD

**Issue by zhangjianbinJAVA** [rolando/scrapy-redis#39]
你好!,怎么实现多个爬虫分布式爬取多个网站的新闻文章呢,是不是每个新闻网站的建一个爬虫呢,谢谢.

**Comment by euangelion666** [comment]
我基本是这样做的，如果你比较厉害的话我觉得可以想办法识别不同的网站来源，这样或许可以一个爬虫，用不同的函数分析内容

**Comment by liugehao** [comment]
最好别搅到一起，  哪个网站改版，调整什么的， 代码一砣一砣的， 不好改

**Comment by zhangjianbinJAVA** [comment]
我看了你的这个scrapy-redis 项目,写的真不错,但是我想实现同时爬取多个网站上的新闻页面,不知有没有好的办法来实现呢,基于你的这个项目可以实现吗,谢谢你的回答!

**Comment by liugehao** [comment]
同时爬取多个网站新闻， 和scrapy-redis一点关系没有，  这个项目只是实现个 
队列， 用来分布式爬取。简单说就是开N个进程爬取一个网站，当然可以同时爬取 
多个网站， 开更多进程 。
它利用redis来处理队列， 去重等， 和你的问题不相干。


在 15/Sep/15 16:11, zhangjianbinJAVA 写道:
> rapy-redis 项目,写的真不错,但是我想实现同时爬取多个网站上的新闻页面,不 
> 知有没有好的办法来实现呢,基于你的这个项目可以实现吗,谢谢你的回答!

**Comment by rolando** [comment]
@liugehao Thank you for replying to this question.
