### ISSUE TITLE
Spider doesn't fetch more urls from redis

### ISSUE THREAD

**Issue by bergonzzi** [rolando/scrapy-redis#40]
Hi, I'm trying to use the RedisMixin in order to crawl some 250.000 urls from multiple machines. It's working fine, although I have an issue whereby some spiders just stop fetching more urls from the redis queue even though there are more to fetch. For example, at some point the spider just idles and says:

    [scrapy] INFO: Crawled 74 pages (at 0 pages/min), scraped 71 items (at 0 items/min)
    [scrapy] INFO: Crawled 74 pages (at 0 pages/min), scraped 71 items (at 0 items/min)
    [scrapy] INFO: Crawled 74 pages (at 0 pages/min), scraped 71 items (at 0 items/min)
    ...

Any idea what might cause this?

**Comment by rolando** [comment]
Do this happen to only few instances of the spider? What happens if you restart the spider that becomes idle? How are you feeding the 250.000 URLs to redis? Could you try running the example spider `myspider_redis` against those URLs?

**Comment by bergonzzi** [comment]
It seems to happen to any instance I launch, it eventually idles and doesn't get more urls. If I restart the problematic spider it just continues where it left of, until it eventually idles again (I'm using `SCHEDULER_PERSIST = True`). I'm feeding the urls with a simple script that loops over a text file containing the urls and doing an rpush. I'm gonna try it out with the example spider as you suggested and post the results here.

**Comment by bergonzzi** [comment]
Ok so I just tested it with the example `myspider_redis.py` (with an empty parse method) and the problem persists. I fired up 3 scrapy instances on different machines, all reading from the same redis instance. 

Instance 1: still running
Instance 2: idled after 141 crawled pages
Instance 3: idled after 544 crawled pages

The only redis-specific settings I have are these:

    SCHEDULER = 'scrapy_redis.scheduler.Scheduler'
    SCHEDULER_QUEUE_CLASS = 'scrapy_redis.queue.SpiderQueue'
    SCHEDULER_PERSIST = True

Other than that I just have some settings for download timeout, redirects, etc. If I restart these instances they just continue crawling for a while until they idle again.

Thanks for any tips you might have.

**Comment by rolando** [comment]
Thanks for your reply, I will try to reproduce this in the following days.

Rolando

**Comment by rocdeng** [comment]
I've met the same problem. Only one machine still fetch jobs from the redis and others freezed. I use 10 machines and 100000 urls. And when I use 3 machines and 10000 redis job, 3 machines worked fine.

**Comment by mrluanma** [comment]
redis-py set [`None` as default timeout](https://github.com/andymccurdy/redis-py/blob/1c2071762ad9b9288e786665990083e61c1cf355/redis/connection.py#L392) may cause connection hang up forever.

**Comment by rafaelcapucho** [comment]
@mrluanma How do you solved that?  Did you insert a timeout in `scrapy_redis.connection.from_settings`?

```
def from_settings(settings):
    url = settings.get('REDIS_URL',  REDIS_URL)
    host = settings.get('REDIS_HOST', REDIS_HOST)
    port = settings.get('REDIS_PORT', REDIS_PORT)

    # REDIS_URL takes precedence over host/port specification.
    if url:
        return redis.from_url(url)
    else:
        return redis.Redis(host=host, port=port)
```

I'm not suffering this problem yet, under development but it appears to be pertinent.

Maybe we should apply timeout connection with an retry decorator, kind of:

```
class handle_errors(object):
    def __init__(self, f):
        self.f = f

    def __call__(self, *args, **kwargs):

        while True:
            try:
                return self.f(*args, **kwargs)
                break

            except (redis.InvalidResponse,
                    redis.ConnectionError,
                    redis.DataError,
                    redis.ResponseError,
                    redis.RedisError,
                    redis.TimeoutError,
                    redis.AuthenticationError,
                    redis.BusyLoadingError,
                    redis.PubSubError,
                    redis.WatchError,
                    TypeError) as e: pass
```

**Comment by rolando** [comment]
In the next release you will be able to override the redis class via setting:

```
REDIS_PARAMS = {
    "redis_cls": "myproject.RedisClient",
}
```

In this way you can apply your own retry logic.

**Comment by sandeepsingh** [comment]
Hey can you please suggest solution to this problem.

**Comment by rentianhua** [comment]
> Hi, I'm trying to use the RedisMixin in order to crawl some 250.000 urls from multiple machines. It's working fine, although I have an issue whereby some spiders just stop fetching more urls from the redis queue even though there are more to fetch. For example, at some point the spider just idles and says:
> 
> ```
> [scrapy] INFO: Crawled 74 pages (at 0 pages/min), scraped 71 items (at 0 items/min)
> [scrapy] INFO: Crawled 74 pages (at 0 pages/min), scraped 71 items (at 0 items/min)
> [scrapy] INFO: Crawled 74 pages (at 0 pages/min), scraped 71 items (at 0 items/min)
> ...
> ```
> Any idea what might cause this?

Can i ask you for the solution, I got the same issue

**Comment by echoocking** [comment]
the same issue
