### ISSUE TITLE
Does scrapy-redis bring the concurrency of scrapy down?

### ISSUE THREAD

**Issue by duhoobo** [rolando/scrapy-redis#43]
I notice the connection with Redis server in `scrapy_redis.scheduler.Scheduler` is in blocking mode. Now if it is slowed down for whatever reason, isn't the Twisted event loop handling other ongoing request blocked at the same time?

**Comment by rainnus** [comment]
when I use the Scheduler, my Spider is very slow.

```
INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
```

**Comment by yrik** [comment]
same for me...

**Comment by jpbalarini** [comment]
Same here. Using the Scheduler slows down the crawler to make it nearly unusable.

**Comment by jpbalarini** [comment]
Found what was happening. The problem is with SCHEDULER_IDLE_BEFORE_CLOSE. If I set this to 0 the spider works fine.

**Comment by rolando** [comment]
@jpbalarini good find!

Unfortunately I don't have enough time to look into this. However, could you share what version of redis and redis-py are you using?

**Comment by rolando** [comment]
Try latest release. Includes some improvements as reading start urls in bach size and using connection timeout by default.

**Comment by sandeepsingh** [comment]
Still getting the same issue, please help how to solve this.

**Comment by jxltom** [comment]
It is extremely slow after using scrapy-redis, any idea for solving this problem?

**Comment by ycq0125** [comment]
您好，这是我的代码。
`class AmazonInfoSpider(RedisSpider):`
     ` name = 'amazon_info'`
    `# allowed_domains = ['amazon.com']`
    `# start_urls = [`
   ` #     'https://httpbin.org/ip',`
    `#     'https://httpbin.org/ip',`
   ` #     'https://httpbin.org/ip',`
   ` #     'https://httpbin.org/ip',`
    `#     'https://httpbin.org/ip',`
    `#     'https://httpbin.org/ip',`
   `#     'https://httpbin.org/ip',`
    `#     'https://httpbin.org/ip',`
    `#     'https://httpbin.org/ip',`
   ` #     'https://httpbin.org/ip',]`
    `custom_settings = {`
        `'REDIS_HOST': '127.0.0.1',`
       ` 'REDIS_PORT': 6379,`
        `'DUPEFILTER_CLASS': 'scrapy_redis.dupefilter.RFPDupeFilter',`
        `'SCHEDULER': "scrapy_redis.scheduler.Scheduler",`
        `'SCHEDULER_PERSIST': True,`
        `'SCHEDULER_QUEUE_CLASS': 'scrapy_redis.queue.PriorityQueue',`
        `'DOWNLOAD_DELAY': 5,`
       ` 'RANDOMIZE_DOWNLOAD_DELAY': True,`
        `'CONCURRENT_REQUESTS': 12,`
       ` 'DOWNLOAD_TIMEOUT': 40,`
       ` 'DOWNLOADER_MIDDLEWARES': {`
           ` # 'amazon.middlewares.AmazonHeadersMiddleware': 541,`
           ` # 'amazon.captchabuster.RobotMiddleware': 90,`
           ` 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware': None,`
        `}`
    `}`

    `# def make_requests_from_url(self, url):`
    `#     url = 'https://www.amazon.com/shops/A2T6YTQ54K16KZ?ref_=v_sp_storefront'`
    `#     return scrapy.Request(url, callback=self.parse, dont_filter=True)`

    `def parse(self, response, **kwargs):`
        `print('heihei', response.body)`
当我使用scrapy时len(engine.downloader.active)将是12，但是如果我采用scrapy-redis将会逐渐变小直到成为1。
![image](https://user-images.githubusercontent.com/49603999/99866108-8c878c80-2be9-11eb-94de-fe60f3e4e0fe.png)
这是使用scrapy-redis后的效果，
![image](https://user-images.githubusercontent.com/49603999/99866219-47178f00-2bea-11eb-9724-93ea2d8a8e52.png)
![image](https://user-images.githubusercontent.com/49603999/99866226-58f93200-2bea-11eb-81bf-46ec7c23c753.png)
所以我想请问有什么更好的方法提升效率吗？谢谢您！
