### ISSUE TITLE
cant get the 'start_urls' key from a  given spidername

### ISSUE THREAD

**Issue by aohan237** [rolando/scrapy-redis#48]
IE. if my spider name is  'ralphlauren' ,the spider will open ,but soon closed.  
the screen dont show 'DEBUG: Reading URLs from redis list'

but if  I  change the name to any other different,it will  work .

this really confuse me.   I dont know why it happen

hoping for your  help,many  thanks

**Comment by rolando** [comment]
Sorry for the late response. We would need more details (sample code, log output, etc) in order to reproduce the issue.
