### ISSUE TITLE
Any way to pop redis-queue only if the spider is idle? 

### ISSUE THREAD

**Issue by madzohan** [rolando/scrapy-redis#64]
I want to decrease redis load. If there any way to pop next request from redis-queue only if the spider is idle (not every request) and use origin `queuelib.PriorityQueue` everywhere else?

**Comment by rolando** [comment]
Are you using `RedisSpider`?

Another approach is:

1. The spider on idle does nothing (just raise `DontCloseSpider`)
2. Use `twisted.internet.task.LoopingCall` to read urls from redis at fixed intervals (i.e.: each 5 seconds)

Also you can skip the scrapy-redis scheduler setting if you don't share the crawling queue among multiple processes.
