### ISSUE TITLE
Unable to assign values to request.meta

### ISSUE THREAD

**Issue by nilsdebruin** [rolando/scrapy-redis#65]
Based on the example RedisCrawlSpider I have created an extended version, which should capture the start_url in a meta object. It looks like this doesn't work. Here is the code:

```
from scrapy.linkextractors import LinkExtractor
from scrapy.spiders import Rule
from scrapy.http import Request
from scrapy_redis.spiders import RedisCrawlSpider

deny_domains = ['facebook.com', 'google.com', 'linkedin.com', 'twitter.com', 'youtube.com']

class MyCrawler(RedisCrawlSpider):
    """Spider that reads urls from redis queue (myspider:start_urls)."""
    name = 'mycrawler_redis'
    redis_key = 'mycrawler:start_urls'

    rules = (
        # follow all links
        Rule(LinkExtractor(deny_domains=deny_domains), callback='parse_page', follow=True),
    )

    def make_requests_from_url(self, url):
        """A method that receives a URL and returns a Request object (or a list of Request objects) to scrape.
        This method is used to construct the initial requests in the start_requests() method,
        and is typically used to convert urls to requests.
        """
        return Request(url, dont_filter=True, meta={'start_url': url})

    def __init__(self, *args, **kwargs):
        # Dynamically define the allowed domains list.
        domain = kwargs.pop('domain', '')
        self.allowed_domains = filter(None, domain.split(','))
        super(MyCrawler, self).__init__(*args, **kwargs)

    def parse_page(self, response):
        print response.meta.get('start_url')
        return {
            'url': response.url,
        }
```

I have checked with ipdb that the make_requests_from_url method is triggered,  but when I set an ipdb trace in parse_page, I can't access the response.meta.get('start_url') key. Any help would be appreciated!

**Comment by rolando** [comment]
At first look, I think you want to persist `start_url` in next sub-requests. As noted, `make_requests_from_url` acts on the start urls, but `parse_page` receives responses from whatever requests your rules found, so these requests don't have the `start_url` meta value.

You could override the `CrawlSpider` internal methods, to persist the meta `start_url`, for example here: https://github.com/scrapy/scrapy/blob/1.1/scrapy/spiders/crawl.py#L51

Or you can persist the meta values in a spider middleware: http://doc.scrapy.org/en/latest/topics/spider-middleware.html#writing-your-own-spider-middleware

Something like:

```python
class MySpiderMiddleware(object):

    def process_spider_output(self, response, result, spider):
        for request_or_item in result:
            if isinstance(request_or_item, Request):
                self.persist_meta(response, request_or_item)
            yield request_or_item

    def persist_meta(self, response, request):
        # It is expected to all responses have a start_url meta value.
        request.meta['start_url'] = response.meta['start_url']

**Comment by nilsdebruin** [comment]
Thanks for your answer! I have gone the second route, but I still haven't got the 'start_url' meta key in the parse_page function. I can see that the middleware is activated and working, as I can put ipdb traces in the functions which both get trigged. Maybe I am missing something? Do you have other pointers for me?

**Comment by rolando** [comment]
@nilsdebruin sorry, can't help you more without a reproducible example.

**Comment by nilsdebruin** [comment]
@rolando I can understand! I took your suggestions and put it into the scripts:

mycrawler_redis.py:
`from scrapy.linkextractors import LinkExtractor
from scrapy.spiders import Rule
from scrapy.http import Request
from scrapy_redis.spiders import RedisCrawlSpider
import ipdb

deny_domains = ['facebook.com', 'google.com', 'linkedin.com', 'twitter.com', 'youtube.com']

class MyCrawler(RedisCrawlSpider):
    """Spider that reads urls from redis queue (myspider:start_urls)."""
    name = 'mycrawler_redis'
    redis_key = 'mycrawler:start_urls'

    rules = (
        # follow all links
        Rule(LinkExtractor(deny_domains=deny_domains), callback='parse_page', follow=True),
    )

    def make_requests_from_url(self, url):
        """A method that receives a URL and returns a Request object (or a list of Request objects) to scrape.
		This method is used to construct the initial requests in the start_requests() method,
		and is typically used to convert urls to requests.
		"""
        return Request(url, dont_filter=True, meta={'start_url': url})

    def __init__(self, *args, **kwargs):
        # Dynamically define the allowed domains list.
        domain = kwargs.pop('domain', '')
        self.allowed_domains = filter(None, domain.split(','))
        super(MyCrawler, self).__init__(*args, **kwargs)

    def parse_page(self, response):
        ipdb.set_trace()
        print response.request.meta.get('start_url')
        return {
            'url': response.url,
        }
`

middlewares.py:
`from scrapy.http import Request

class MyCrawlerMiddleware(object):

	def process_spider_output(self, response, result, spider):
		for request_or_item in result:
			if isinstance(request_or_item, Request):
				self.persist_meta(response, request_or_item)
			yield request_or_item

	def persist_meta(self, response, request):
		request.meta['start_url'] = response.meta['start_url']`

As already mentioned, I can see that the middleware functions are being executed. Thanks for the help!
