### ISSUE TITLE
Unordered sets in case of using SADD

### ISSUE THREAD

**Issue by 77cc33** [rolando/scrapy-redis#73]
Hello,

I think it's good to clarify in documentation that SADD creates unordered sets, so all links not processed in the order they were imported. 

> If True, it uses redis' `spop` operation. This could be useful if you
> want to avoid duplicates in your start urls list. In this cases, urls must
> be added via `sadd` command or you will get a type error from redis.
> REDIS_START_URLS_AS_SET = False

Also it's good to clarify if FIFO/FILO will work in this mode.

Thank You

**Comment by rolando** [comment]
Thanks for your input. I've updated the readme.
