### ISSUE TITLE
Add SCHEDULER_FLUSH_ON_START to doc

### ISSUE THREAD

**Issue by podolskyi** [rolando/scrapy-redis#76]
I think make sense add a parameter SCHEDULER_FLUSH_ON_START to documents or example.

**Comment by rolando** [comment]
There is [this note](https://github.com/rolando/scrapy-redis/tree/master/example-project#spiders) in the examples' readme:

```
All requests are persisted by default. You can clear the queue
by using the SCHEDULER_FLUSH_ON_START setting. 
For example: scrapy crawl dmoz -s SCHEDULER_FLUSH_ON_START=1.
```

Is that good enough?

**Comment by podolskyi** [comment]
@rolando Thanks.
yes, enough
not noticed.

**Comment by podolskyi** [comment]
parameter exist in documentation.
