### ISSUE TITLE
Any way to send request again, but not filtered by redis dupefilter?

### ISSUE THREAD

**Issue by alex1993** [rolando/scrapy-redis#78]
For example, if i find the response is not what i want (maybe banned by web server or receive a redirect response), and i want to send the request again.
I tried:
```
if len(response.xpath('some path')) == 0:  
    yield Request(url=response.url, callback=self.parse, dont_filter=True)
```
but the request would still be filtered by redis dupefilter.
How can i send the request again, but not filtered by redis dupefilter?

`dont_filter=True` is not helping.

Thanks for your help.

**Comment by rolando** [comment]
I think you need a custom dupefilter that uses additional information when
making the fingerprint.

Rolando

**Comment by alex1993** [comment]
Got it, thanks for your help~
