### ISSUE TITLE
How can I set redis key  expiration time

### ISSUE THREAD

**Issue by ben0x007** [rolando/scrapy-redis#84]
I want to set url a expiration  time

**Comment by rolando** [comment]
You can expire a key with the [EXPIRE](https://redis.io/commands/expire) command but, as far I can tell, you can't expire a single url as a member of a list/set.

You could use a workaround like adding a timestamp with the URL so the spiders can skip it. Otherwise you can opt for more full-featured projects like [frontera](https://github.com/scrapinghub/frontera).

**Comment by cj1205** [comment]
Considering this scenario,
One spider already crawl one website over months, so **:dupeFilter** will have a lot of fingureprint, but the content of some URLs may already updated, so if we can set expire time like one month for each old fingureprint, it will be removed from **:dupeFilter**, the spider will get one chance to fetch the latest chance.

As far as I know, scrapy_redis save the **dupeFilter** into one zset, which make expire time not implementable for each fingureprint.

But can we have one feature request which will save each fingureprint of **dupeFilter** as redis.type=string? then we can add one configuration in setting.py like FINGUREPRINT_EXPIRE = 3600 (seconds/minutes etc).

Thanks.

**Comment by rmax** [comment]
@cj1205 your scenario would require another approach. Like storing each `(fingerprint, expire_at)` as tuple or using fingerprint as key and expiration as value. So you can check the on read time whether or not the fingerprint has expired.

**Comment by toxicbuzzer** [comment]
In the scrapy-redis folder, edit file "dupefilter.py" and after line 102 (should read "added = self.server.sadd(self.key, fp)") add this line of code straight after it "self.server.expire(self.key,60*1440,1)". (60*1440 means... expire in 1 day)

If you want to add a CONST in the scrapy settings folder, this is also do-able within dupefilter.py but requires a little bit of coding.
