### ISSUE TITLE
Can't find the latest version on pypi

### ISSUE THREAD

**Issue by xuexingdong** [rolando/scrapy-redis#88]
The versions after 0.6.4, which solve the python3 str problem are not published to pypi. So I can't use the pipreqs module to generate requirements.txt and use it in my project. Can you publish it at your convenience? Thanks a lot.

**Comment by rolando** [comment]
Oh, thank you for the report. An update in the author's emails broke the automated PyPI deployment from Travis CI.

New release has been effectively published.
