### ISSUE TITLE
KeyError: Spider not found

### ISSUE THREAD

**Issue by Range0122** [rolando/scrapy-redis#89]
sorry to bother you here.  my English is poor. :)  
I wrote a scrapy used RedisCrawlSpider imitated by yours. 
Firstly it didnt work. And I managed making it work in docker, and there could be four crawler working in docker. unfortunately, they could only start but scrapying.

Following are the error:
 
crawler_1  | /usr/local/lib/python2.7/site-packages/scrapy/spiderloader.py:37: RuntimeWarning:
crawler_1  | Traceback (most recent call last):
crawler_1  |   File "/usr/local/lib/python2.7/site-packages/scrapy/spiderloader.py", line 31, in _load_all_spiders
crawler_1  |     for module in walk_modules(name):
crawler_1  |   File "/usr/local/lib/python2.7/site-packages/scrapy/utils/misc.py", line 71, in walk_modules
crawler_1  |     submod = import_module(fullpath)
crawler_1  |   File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
crawler_1  |     __import__(name)
crawler_1  |   File "/usr/src/app/ZhihuSpider/spiders/zh_spider.py", line 8, in <module>
crawler_1  |     from bs4 import BeautifulSoup
crawler_1  | ImportError: No module named bs4
crawler_1  | Could not load spiders from module 'ZhihuSpider.spiders'. Check SPIDER_MODULES setting
crawler_1  |   warnings.warn(msg, RuntimeWarning)
crawler_1  | 2017-03-02 11:55:39 [scrapy.utils.log] INFO: Scrapy 1.3.2 started (bot: ZhihuSpider)
crawler_1  | 2017-03-02 11:55:39 [scrapy.utils.log] INFO: Overridden settings: {'NEWSPIDER_MODULE': 'ZhihuSpider.spiders', 'ROBOTSTXT_OBEY': True, 'DEPTH_LIMIT': 20, 'SPIDER_MODULES': ['ZhihuSpider.spiders'], 'BOT_NAME': 'ZhihuSpider', 'COOKIES_ENABLED': False}
crawler_1  | Traceback (most recent call last):
crawler_1  |   File "/usr/local/bin/scrapy", line 11, in <module>
crawler_1  |     sys.exit(execute())
crawler_1  |   File "/usr/local/lib/python2.7/site-packages/scrapy/cmdline.py", line 142, in execute
crawler_1  |     _run_print_help(parser, _run_command, cmd, args, opts)
crawler_1  |   File "/usr/local/lib/python2.7/site-packages/scrapy/cmdline.py", line 88, in _run_print_help
crawler_1  |     func(*a, **kw)
crawler_1  |   File "/usr/local/lib/python2.7/site-packages/scrapy/cmdline.py", line 149, in _run_command
crawler_1  |     cmd.run(args, opts)
crawler_1  |   File "/usr/local/lib/python2.7/site-packages/scrapy/commands/crawl.py", line 57, in run
crawler_1  |     self.crawler_process.crawl(spname, **opts.spargs)
crawler_1  |   File "/usr/local/lib/python2.7/site-packages/scrapy/crawler.py", line 162, in crawl
crawler_1  |     crawler = self.create_crawler(crawler_or_spidercls)
crawler_1  |   File "/usr/local/lib/python2.7/site-packages/scrapy/crawler.py", line 190, in create_crawler
crawler_1  |     return self._create_crawler(crawler_or_spidercls)
crawler_1  |   File "/usr/local/lib/python2.7/site-packages/scrapy/crawler.py", line 194, in _create_crawler
crawler_1  |     spidercls = self.spider_loader.load(spidercls)
crawler_1  |   File "/usr/local/lib/python2.7/site-packages/scrapy/spiderloader.py", line 51, in load
crawler_1  |     raise KeyError("Spider not found: {}".format(spider_name))
crawler_1  | KeyError: 'Spider not found: zh_spider'

Thanks for helping, please.

**Comment by rolando** [comment]
> crawler_1 | ImportError: No module named bs4

Looks like your spider code fails to load due to a missing dependency, hence the `KeyError` failure.

**Comment by Range0122** [comment]
I load bs4 in my code by 'from bs4 import BeautifulSoup'，and it work if I run it by ‘scrapy crawl spidername’.

https://github.com/Range0122/ZhihuSpider

Here's my code. I'll be appreciate if you could watch it. :)
(So sorry to bother.)

**Comment by Range0122** [comment]
Also, it works well when I try command 'scrapy crawl zh_spider' and then 'redis-cli lpush myspider:start_urls http://xxxx.com'

**Comment by rolando** [comment]
When it doesn't work?

**Comment by Range0122** [comment]
sorry that my computer broke down yesterday, so i have to reinstall windows again......   :(
I got new problem today:

crawler_1  | 2017-03-04 08:03:37 [twisted] CRITICAL:
crawler_1  | Traceback (most recent call last):
crawler_1  |   File "/usr/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1301, in _inlineCallbacks
crawler_1  |     result = g.send(result)
crawler_1  |   File "/usr/local/lib/python2.7/site-packages/scrapy/crawler.py", line 90, in crawl
crawler_1  |     six.reraise(*exc_info)
crawler_1  |   File "/usr/local/lib/python2.7/site-packages/scrapy/crawler.py", line 74, in crawl
crawler_1  |     yield self.engine.open_spider(self.spider, start_requests)
crawler_1  | ConnectionError: Error 111 connecting to 127.0.0.1:6379. Connection refused.

But this time I could clearly see that when i put 'docker-compose up', it begins to install the python packages mentioned in requirements.txt
After that, the error occured.......  I'm already overwhelmed...

**Comment by rolando** [comment]
That error means the redis instance is not up or is configured in other host/port.

**Comment by Range0122** [comment]
Amazing!!!
I closed the redis-server which I open myself, the spider works well!
In fact, I considered that is necessary to open the redis-server on my own.
Thanks for helping!
