### ISSUE TITLE
DEBUG: Request not made from data

### ISSUE THREAD

**Issue by n1kt0** [rolando/scrapy-redis#92]
I have an issue regarding the debug message mentioned in the title.

I am putting raw links as strings in the redis queue xxx:start_urls and I'm getting the the error message: 

`DEBUG: Request not made from data b'http://www.xxx.com'`

When I turn on in scrapy-redis the redis decode_responses option I still get the same error but this time without the b in front of the url:

`DEBUG: Request not made from data 'http://www.xxx.com'
`

**Comment by n1kt0** [comment]
It was again my failure again! I had to provide the function

`def make_requests_from_url(self, url):
"""Returns a request to be scheduled or none."""
        return scrapy.Request(url)
`
this is the most minimalistic version of that function.

**Comment by n1kt0** [comment]
One more sentence for clarification. You don't have to provide that function. I've been reading through some pages of the scrapy documentation, encountered that function and pasted it empty in my code with a pass statement for later use. That is why I had these problems.

**Comment by EverydayLearning** [comment]
Now I have the same problem, how did you solve it?

**Comment by n1kt0** [comment]
did you redefine this function? if so delete it, I think you shouldn't redefine it if you don't have a reason since it is implemented in it's simplest way in some base class, if I remember right...
